# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(blank=True, max_length=155, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True, verbose_name='Other details')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.Product'),
        ),
    ]
