# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-02 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_auto_20181227_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_name',
            new_name='customer_name',
        ),
    ]
