# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0008_customer_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quantity',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
