# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0009_customer_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
