# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-21 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0011_auto_20190201_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
